/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Zona } from '../../models/zona';

export interface ApiZonasZonasGet$Json$Params {
  parroquiaId?: string;
}

export function apiZonasZonasGet$Json(http: HttpClient, rootUrl: string, params?: ApiZonasZonasGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Zona>>> {
  const rb = new RequestBuilder(rootUrl, apiZonasZonasGet$Json.PATH, 'get');
  if (params) {
    rb.query('parroquiaId', params.parroquiaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Zona>>;
    })
  );
}

apiZonasZonasGet$Json.PATH = '/api/Zonas/zonas';
