/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Canton } from '../../models/canton';

export interface ApiZonasCantonesGet$Json$Params {
  provinciaId?: string;
}

export function apiZonasCantonesGet$Json(http: HttpClient, rootUrl: string, params?: ApiZonasCantonesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Canton>>> {
  const rb = new RequestBuilder(rootUrl, apiZonasCantonesGet$Json.PATH, 'get');
  if (params) {
    rb.query('provinciaId', params.provinciaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Canton>>;
    })
  );
}

apiZonasCantonesGet$Json.PATH = '/api/Zonas/cantones';
