/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MesaElectoralDtoPaginacionDto } from '../../models/mesa-electoral-dto-paginacion-dto';
import { TipoMesa } from '../../models/tipo-mesa';

export interface ApiMesasElectoralPaginacionGet$Json$Params {
  eleccionId?: string;
  pagina?: number;
  pageSize?: number;
  busqueda?: string;
  tipoMesa?: TipoMesa;
}

export function apiMesasElectoralPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiMesasElectoralPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MesaElectoralDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiMesasElectoralPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('busqueda', params.busqueda, {});
    rb.query('tipoMesa', params.tipoMesa, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MesaElectoralDtoPaginacionDto>;
    })
  );
}

apiMesasElectoralPaginacionGet$Json.PATH = '/api/MesasElectoral/paginacion';
