/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MesaElectoral } from '../../models/mesa-electoral';

export interface ApiMesasElectoralLotePost$Plain$Params {
  eleccionId?: string;
  zonaId?: string;
  cantidadFemeninas?: number;
  cantidadMasculinas?: number;
}

export function apiMesasElectoralLotePost$Plain(http: HttpClient, rootUrl: string, params?: ApiMesasElectoralLotePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MesaElectoral>> {
  const rb = new RequestBuilder(rootUrl, apiMesasElectoralLotePost$Plain.PATH, 'post');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('zonaId', params.zonaId, {});
    rb.query('cantidadFemeninas', params.cantidadFemeninas, {});
    rb.query('cantidadMasculinas', params.cantidadMasculinas, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MesaElectoral>;
    })
  );
}

apiMesasElectoralLotePost$Plain.PATH = '/api/MesasElectoral/lote';
