/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MesaElectoralDto } from '../../models/mesa-electoral-dto';
import { TipoCandidato } from '../../models/tipo-candidato';

export interface ApiMesasElectoralDisponiblePorZonaGet$Json$Params {
  eleccionId?: string;
  zonaId?: string;
  tipoCandidato?: TipoCandidato;
}

export function apiMesasElectoralDisponiblePorZonaGet$Json(http: HttpClient, rootUrl: string, params?: ApiMesasElectoralDisponiblePorZonaGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MesaElectoralDto>>> {
  const rb = new RequestBuilder(rootUrl, apiMesasElectoralDisponiblePorZonaGet$Json.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('zonaId', params.zonaId, {});
    rb.query('tipoCandidato', params.tipoCandidato, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MesaElectoralDto>>;
    })
  );
}

apiMesasElectoralDisponiblePorZonaGet$Json.PATH = '/api/MesasElectoral/disponible-por-zona';
