/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MesaElectoralDto } from '../../models/mesa-electoral-dto';

export interface ApiMesasElectoralIdGet$Plain$Params {
  id: string;
}

export function apiMesasElectoralIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiMesasElectoralIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MesaElectoralDto>> {
  const rb = new RequestBuilder(rootUrl, apiMesasElectoralIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MesaElectoralDto>;
    })
  );
}

apiMesasElectoralIdGet$Plain.PATH = '/api/MesasElectoral/{id}';
