/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoMesa } from '../../models/tipo-mesa';

export interface ApiMesasElectoralCodigoMesaGet$Params {
  eleccionId?: string;
  zonaId?: string;
  tipoMesa?: TipoMesa;
}

export function apiMesasElectoralCodigoMesaGet(http: HttpClient, rootUrl: string, params?: ApiMesasElectoralCodigoMesaGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiMesasElectoralCodigoMesaGet.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('zonaId', params.zonaId, {});
    rb.query('tipoMesa', params.tipoMesa, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiMesasElectoralCodigoMesaGet.PATH = '/api/MesasElectoral/codigo-mesa';
