/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResultadoEleccionDto } from '../../models/resultado-eleccion-dto';
import { TipoCandidato } from '../../models/tipo-candidato';
import { TipoResultado } from '../../models/tipo-resultado';

export interface ApiResultadosEleccionParroquiaGet$Json$Params {
  eleccionId?: string;
  parroquiaId?: string;
  tipoCandidato?: TipoCandidato;
  tipoResultado?: TipoResultado;
}

export function apiResultadosEleccionParroquiaGet$Json(http: HttpClient, rootUrl: string, params?: ApiResultadosEleccionParroquiaGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ResultadoEleccionDto>> {
  const rb = new RequestBuilder(rootUrl, apiResultadosEleccionParroquiaGet$Json.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('parroquiaId', params.parroquiaId, {});
    rb.query('tipoCandidato', params.tipoCandidato, {});
    rb.query('tipoResultado', params.tipoResultado, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultadoEleccionDto>;
    })
  );
}

apiResultadosEleccionParroquiaGet$Json.PATH = '/api/Resultados/eleccion/parroquia';
