/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActaDtoPaginacionDto } from '../../models/acta-dto-paginacion-dto';
import { EstadoActa } from '../../models/estado-acta';
import { TipoCandidato } from '../../models/tipo-candidato';

export interface ApiActasPaginacionGet$Json$Params {
  eleccionId?: string;
  pagina?: number;
  pageSize?: number;
  provinciaId?: string;
  cantonId?: string;
  parroquiaId?: string;
  zonaId?: string;
  mesaId?: string;
  estadoActa?: EstadoActa;
  tipoCandidato?: TipoCandidato;
}

export function apiActasPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiActasPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ActaDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiActasPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('provinciaId', params.provinciaId, {});
    rb.query('cantonId', params.cantonId, {});
    rb.query('parroquiaId', params.parroquiaId, {});
    rb.query('zonaId', params.zonaId, {});
    rb.query('mesaId', params.mesaId, {});
    rb.query('estadoActa', params.estadoActa, {});
    rb.query('tipoCandidato', params.tipoCandidato, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActaDtoPaginacionDto>;
    })
  );
}

apiActasPaginacionGet$Json.PATH = '/api/Actas/paginacion';
