/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActaEleccion } from '../../models/acta-eleccion';

export interface ApiActasPost$Json$Params {
      body?: ActaEleccion
}

export function apiActasPost$Json(http: HttpClient, rootUrl: string, params?: ApiActasPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ActaEleccion>> {
  const rb = new RequestBuilder(rootUrl, apiActasPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActaEleccion>;
    })
  );
}

apiActasPost$Json.PATH = '/api/Actas';
