/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActaDetalleDto } from '../../models/acta-detalle-dto';
import { TipoCandidato } from '../../models/tipo-candidato';

export interface ApiActasCandidatosListasRegistroGet$Plain$Params {
  eleccionId?: string;
  tipoCandidato?: TipoCandidato;
  provinciaId?: string;
  cantonId?: string;
  parroquiaId?: string;
}

export function apiActasCandidatosListasRegistroGet$Plain(http: HttpClient, rootUrl: string, params?: ApiActasCandidatosListasRegistroGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActaDetalleDto>>> {
  const rb = new RequestBuilder(rootUrl, apiActasCandidatosListasRegistroGet$Plain.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('tipoCandidato', params.tipoCandidato, {});
    rb.query('provinciaId', params.provinciaId, {});
    rb.query('cantonId', params.cantonId, {});
    rb.query('parroquiaId', params.parroquiaId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActaDetalleDto>>;
    })
  );
}

apiActasCandidatosListasRegistroGet$Plain.PATH = '/api/Actas/candidatos-listas-registro';
