/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoActa } from '../../models/estado-acta';

export interface ApiActasCambiarEstadoIdPut$Params {
  id: string;
  nuevoEstado?: EstadoActa;
}

export function apiActasCambiarEstadoIdPut(http: HttpClient, rootUrl: string, params: ApiActasCambiarEstadoIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiActasCambiarEstadoIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('nuevoEstado', params.nuevoEstado, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiActasCambiarEstadoIdPut.PATH = '/api/Actas/cambiarEstado/{id}';
