/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActaDtoPaginacionDto } from '../../models/acta-dto-paginacion-dto';

export interface ApiActasPaginacionGet$Plain$Params {
  eleccionId?: string;
  pagina?: number;
  pageSize?: number;
}

export function apiActasPaginacionGet$Plain(http: HttpClient, rootUrl: string, params?: ApiActasPaginacionGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ActaDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiActasPaginacionGet$Plain.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActaDtoPaginacionDto>;
    })
  );
}

apiActasPaginacionGet$Plain.PATH = '/api/Actas/paginacion';
