/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RolDtoPaginacionDto } from '../../models/rol-dto-paginacion-dto';

export interface ApiRolesPaginacionGet$Json$Params {
  pagina?: number;
  pageSize?: number;
  buscar?: string;
}

export function apiRolesPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiRolesPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RolDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiRolesPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('buscar', params.buscar, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RolDtoPaginacionDto>;
    })
  );
}

apiRolesPaginacionGet$Json.PATH = '/api/Roles/paginacion';
