/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RolDto } from '../../models/rol-dto';

export interface ApiRolesPost$Plain$Params {
      body?: RolDto
}

export function apiRolesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiRolesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RolDto>> {
  const rb = new RequestBuilder(rootUrl, apiRolesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RolDto>;
    })
  );
}

apiRolesPost$Plain.PATH = '/api/Roles';
