/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ActasService } from './services/actas.service';
export { AuthService } from './services/auth.service';
export { BitacoraService } from './services/bitacora.service';
export { CandidatosService } from './services/candidatos.service';
export { EleccionesService } from './services/elecciones.service';
export { ListasElectoralService } from './services/listas-electoral.service';
export { MesasElectoralService } from './services/mesas-electoral.service';
export { ResultadosService } from './services/resultados.service';
export { RolesService } from './services/roles.service';
export { UsuariosService } from './services/usuarios.service';
export { ZonasService } from './services/zonas.service';
