/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BitacoraDtoPaginacionDto } from '../../models/bitacora-dto-paginacion-dto';

export interface ApiBitacoraPaginacionGet$Json$Params {
  pagina?: number;
  pageSize?: number;
  fechaDesde?: string;
  fechaHasta?: string;
  usuarioId?: string;
  accion?: string;
  tabla?: string;
}

export function apiBitacoraPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiBitacoraPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BitacoraDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiBitacoraPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('fechaDesde', params.fechaDesde, {});
    rb.query('fechaHasta', params.fechaHasta, {});
    rb.query('usuarioId', params.usuarioId, {});
    rb.query('accion', params.accion, {});
    rb.query('tabla', params.tabla, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BitacoraDtoPaginacionDto>;
    })
  );
}

apiBitacoraPaginacionGet$Json.PATH = '/api/Bitacora/paginacion';
