/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BitacoraDto } from '../../models/bitacora-dto';

export interface ApiBitacoraRegistroGet$Plain$Params {
  tabla?: string;
  idRegistro?: string;
}

export function apiBitacoraRegistroGet$Plain(http: HttpClient, rootUrl: string, params?: ApiBitacoraRegistroGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BitacoraDto>>> {
  const rb = new RequestBuilder(rootUrl, apiBitacoraRegistroGet$Plain.PATH, 'get');
  if (params) {
    rb.query('tabla', params.tabla, {});
    rb.query('idRegistro', params.idRegistro, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BitacoraDto>>;
    })
  );
}

apiBitacoraRegistroGet$Plain.PATH = '/api/Bitacora/registro';
