/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BitacoraDto } from '../../models/bitacora-dto';

export interface ApiBitacoraIdGet$Json$Params {
  bitacoraId?: string;
}

export function apiBitacoraIdGet$Json(http: HttpClient, rootUrl: string, params?: ApiBitacoraIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BitacoraDto>> {
  const rb = new RequestBuilder(rootUrl, apiBitacoraIdGet$Json.PATH, 'get');
  if (params) {
    rb.query('bitacoraId', params.bitacoraId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BitacoraDto>;
    })
  );
}

apiBitacoraIdGet$Json.PATH = '/api/Bitacora/id';
