/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Eleccion } from '../../models/eleccion';

export interface ApiEleccionesGet$Plain$Params {
}

export function apiEleccionesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiEleccionesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Eleccion>>> {
  const rb = new RequestBuilder(rootUrl, apiEleccionesGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Eleccion>>;
    })
  );
}

apiEleccionesGet$Plain.PATH = '/api/Elecciones';
