/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Eleccion } from '../../models/eleccion';

export interface ApiEleccionesIdGet$Plain$Params {
  id: string;
}

export function apiEleccionesIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiEleccionesIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Eleccion>> {
  const rb = new RequestBuilder(rootUrl, apiEleccionesIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Eleccion>;
    })
  );
}

apiEleccionesIdGet$Plain.PATH = '/api/Elecciones/{id}';
