/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Eleccion } from '../../models/eleccion';

export interface ApiEleccionesPost$Plain$Params {
      body?: Eleccion
}

export function apiEleccionesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiEleccionesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Eleccion>> {
  const rb = new RequestBuilder(rootUrl, apiEleccionesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Eleccion>;
    })
  );
}

apiEleccionesPost$Plain.PATH = '/api/Elecciones';
