/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActaDto } from '../models/acta-dto';
export interface ActaDtoPaginacionDto {
  items?: Array<ActaDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
