/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActaDetalleDto {
  candidato?: string | null;
  candidatoId?: string | null;
  lista?: string | null;
  listaElectoralId?: string;
  numeroLista?: number;
  votos?: number;
}
