/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActaDetalleDto } from '../models/acta-detalle-dto';
import { EstadoActa } from '../models/estado-acta';
import { TipoCandidato } from '../models/tipo-candidato';
export interface ActaDto {
  actasDetalle?: Array<ActaDetalleDto> | null;
  canton?: string | null;
  codigoMesa?: string | null;
  descripcionEleccion?: string | null;
  descripcionMesa?: string | null;
  eleccion?: string | null;
  estado?: EstadoActa;
  fechaRegistro?: string;
  idActa?: string;
  parroquia?: string | null;
  provincia?: string | null;
  tipoCandidato?: TipoCandidato;
  totalVotos?: number;
  votosBlancos?: number;
  votosNulos?: number;
  zona?: string | null;
}
