/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActaDetalle {
  actaId?: string;
  candidatoId?: string | null;
  idActaDetalle?: string;
  listaElectoralId?: string;
  votos?: number;
}
