/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActaDetalleDto {
  candidatoId?: string | null;
  listaElectoralId?: string;
  nombreCandidato?: string | null;
  nombreLista?: string | null;
  numeroLista?: number;
  votos?: number;
}
