/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdmUsuario {
  emailUsuario?: string | null;
  estado?: boolean;
  fechaCreacion?: string;
  idUsuario?: string;
  nombreUsuario?: string;
  password?: string | null;
  rolId?: string;
}
