/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BitacoraDto {
  accion?: string | null;
  correoUsuario?: string | null;
  descripcion?: string | null;
  fechaRegistro?: string;
  idBitacora?: string;
  tabla?: string | null;
  usuario?: string | null;
  valoresAnteriores?: string | null;
  valoresNuevos?: string | null;
}
