/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BitacoraDto } from '../models/bitacora-dto';
export interface BitacoraDtoPaginacionDto {
  items?: Array<BitacoraDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
