/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaCandidatoDto } from '../models/lista-candidato-dto';
import { TipoCandidato } from '../models/tipo-candidato';
export interface CandidatoDto {
  activo?: boolean;
  descripcionEleccion?: string | null;
  eleccion?: string | null;
  idCandidato?: string;
  listasCandidato?: Array<ListaCandidatoDto> | null;
  nombreCandidato?: string | null;
  orden?: number | null;
  tipoCandidato?: TipoCandidato;
}
