/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CandidatoDto } from '../models/candidato-dto';
export interface CandidatoDtoPaginacionDto {
  items?: Array<CandidatoDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
