/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaCandidato } from '../models/lista-candidato';
import { TipoCandidato } from '../models/tipo-candidato';
export interface Candidato {
  activo?: boolean;
  eleccionId?: string;
  idCandidato?: string;
  listaCandidatos?: Array<ListaCandidato> | null;
  nombreCandidato?: string;
  orden?: number | null;
  tipoCandidato?: TipoCandidato;
}
