/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEleccion } from '../models/estado-eleccion';
export interface Eleccion {
  descripcion?: string | null;
  estado?: EstadoEleccion;
  fechaCreacion?: string;
  fechaEleccion?: string;
  fechaModificacion?: string | null;
  idEleccion?: string;
  nombreEleccion?: string;
}
