/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEleccion } from './estado-eleccion';

/**
 * Each possible value of `EstadoEleccion`
 */
export const ESTADO_ELECCION: EstadoEleccion[] = [
  'Planificada',
  'Activa',
  'Cerrada'
];