/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoActa } from './estado-acta';

/**
 * Each possible value of `EstadoActa`
 */
export const ESTADO_ACTA: EstadoActa[] = [
  'Registrada',
  'EnRevision',
  'ConInconsistencia',
  'Validada',
  'Anulada'
];