/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Jurisdiccion } from './jurisdiccion';

/**
 * Each possible value of `Jurisdiccion`
 */
export const JURISDICCION: Jurisdiccion[] = [
  'Nacional',
  'Provincial',
  'Cantonal',
  'Circunscripcion'
];