/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaCandidatoDto {
  esPrincipal?: boolean;
  listaElectoralId?: string;
  nombreLista?: string | null;
  numeroLista?: number;
}
