/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaCandidato {
  candidatoId?: string;
  idListaCandidato?: string;
  listaElectoralId?: string;
  listaPrincipal?: boolean;
}
