/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaElectoral } from '../models/lista-electoral';
export interface ListaElectoralPaginacionDto {
  items?: Array<ListaElectoral> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
