/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginResponseDto {
  expiracionToken?: string;
  idUsuario?: string;
  nombreRol?: string | null;
  nombreUsuario?: string | null;
  rolId?: string;
  token?: string | null;
}
