/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MesaElectoralDto } from '../models/mesa-electoral-dto';
export interface MesaElectoralDtoPaginacionDto {
  items?: Array<MesaElectoralDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
