/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Provincia {
  activo?: boolean;
  codigoProvincia?: string;
  idProvincia?: string;
  nombreProvincia?: string;
}
