/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResultadoDetalleDto } from '../models/resultado-detalle-dto';
export interface ResultadoEleccionDto {
  mesasConInconsistencia?: number;
  mesasEnRevision?: number;
  mesasRegistradas?: number;
  mesasValidadas?: number;
  resultados?: Array<ResultadoDetalleDto> | null;
  totalMesas?: number;
  totalVotos?: number;
  totalVotosBlancos?: number;
  totalVotosNulos?: number;
  totalVotosValidos?: number;
}
