/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RolDto {
  activo?: boolean;
  descripcionRol?: string | null;
  idRol?: string;
  nombreRol?: string | null;
  permisos?: Array<string> | null;
}
