/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolDto } from '../models/rol-dto';
export interface RolDtoPaginacionDto {
  items?: Array<RolDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
