/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoMesa } from './tipo-mesa';

/**
 * Each possible value of `TipoMesa`
 */
export const TIPO_MESA: TipoMesa[] = [
  'Femenina',
  'Masculina'
];