/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoCandidato } from './tipo-candidato';

/**
 * Each possible value of `TipoCandidato`
 */
export const TIPO_CANDIDATO: TipoCandidato[] = [
  'Presidente',
  'Prefecto',
  'Alcalde',
  'ConcejalUrbano',
  'ConcejalRural'
];