/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoResultado } from './tipo-resultado';

/**
 * Each possible value of `TipoResultado`
 */
export const TIPO_RESULTADO: TipoResultado[] = [
  'Oficial',
  'Preliminar'
];