/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioDto } from '../models/usuario-dto';
export interface UsuarioDtoPaginacionDto {
  items?: Array<UsuarioDto> | null;
  pageActual?: number;
  pageSize?: number;
  totalPages?: number;
  totalRegistros?: number;
}
