/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioDto {
  emailUsuario?: string | null;
  estado?: boolean;
  fechaCreacion?: string;
  idUsuario?: string;
  nombreRol?: string | null;
  nombreUsuario?: string | null;
  rolId?: string;
}
