/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ActaDto } from '../models/acta-dto';
import { ActaDtoPaginacionDto } from '../models/acta-dto-paginacion-dto';
import { ActaEleccion } from '../models/acta-eleccion';
import { apiActasCambiarEstadoIdPut } from '../fn/actas/api-actas-cambiar-estado-id-put';
import { ApiActasCambiarEstadoIdPut$Params } from '../fn/actas/api-actas-cambiar-estado-id-put';
import { apiActasIdGet$Json } from '../fn/actas/api-actas-id-get-json';
import { ApiActasIdGet$Json$Params } from '../fn/actas/api-actas-id-get-json';
import { apiActasIdGet$Plain } from '../fn/actas/api-actas-id-get-plain';
import { ApiActasIdGet$Plain$Params } from '../fn/actas/api-actas-id-get-plain';
import { apiActasIdPut } from '../fn/actas/api-actas-id-put';
import { ApiActasIdPut$Params } from '../fn/actas/api-actas-id-put';
import { apiActasMesaMesaIdGet$Json } from '../fn/actas/api-actas-mesa-mesa-id-get-json';
import { ApiActasMesaMesaIdGet$Json$Params } from '../fn/actas/api-actas-mesa-mesa-id-get-json';
import { apiActasMesaMesaIdGet$Plain } from '../fn/actas/api-actas-mesa-mesa-id-get-plain';
import { ApiActasMesaMesaIdGet$Plain$Params } from '../fn/actas/api-actas-mesa-mesa-id-get-plain';
import { apiActasPaginacionGet$Json } from '../fn/actas/api-actas-paginacion-get-json';
import { ApiActasPaginacionGet$Json$Params } from '../fn/actas/api-actas-paginacion-get-json';
import { apiActasPaginacionGet$Plain } from '../fn/actas/api-actas-paginacion-get-plain';
import { ApiActasPaginacionGet$Plain$Params } from '../fn/actas/api-actas-paginacion-get-plain';
import { apiActasPost$Json } from '../fn/actas/api-actas-post-json';
import { ApiActasPost$Json$Params } from '../fn/actas/api-actas-post-json';
import { apiActasPost$Plain } from '../fn/actas/api-actas-post-plain';
import { ApiActasPost$Plain$Params } from '../fn/actas/api-actas-post-plain';

@Injectable({ providedIn: 'root' })
export class ActasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiActasPaginacionGet()` */
  static readonly ApiActasPaginacionGetPath = '/api/Actas/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasPaginacionGet$Plain$Response(params?: ApiActasPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDtoPaginacionDto>> {
    const obs = apiActasPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasPaginacionGet$Plain(params?: ApiActasPaginacionGet$Plain$Params, context?: HttpContext): Promise<ActaDtoPaginacionDto> {
    const resp = this.apiActasPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDtoPaginacionDto>): ActaDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasPaginacionGet$Json$Response(params?: ApiActasPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDtoPaginacionDto>> {
    const obs = apiActasPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasPaginacionGet$Json(params?: ApiActasPaginacionGet$Json$Params, context?: HttpContext): Promise<ActaDtoPaginacionDto> {
    const resp = this.apiActasPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDtoPaginacionDto>): ActaDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiActasIdGet()` */
  static readonly ApiActasIdGetPath = '/api/Actas/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasIdGet$Plain$Response(params: ApiActasIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDto>> {
    const obs = apiActasIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasIdGet$Plain(params: ApiActasIdGet$Plain$Params, context?: HttpContext): Promise<ActaDto> {
    const resp = this.apiActasIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDto>): ActaDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasIdGet$Json$Response(params: ApiActasIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDto>> {
    const obs = apiActasIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasIdGet$Json(params: ApiActasIdGet$Json$Params, context?: HttpContext): Promise<ActaDto> {
    const resp = this.apiActasIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDto>): ActaDto => r.body);
  }

  /** Path part for operation `apiActasIdPut()` */
  static readonly ApiActasIdPutPath = '/api/Actas/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasIdPut$Response(params: ApiActasIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiActasIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasIdPut(params: ApiActasIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiActasIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiActasMesaMesaIdGet()` */
  static readonly ApiActasMesaMesaIdGetPath = '/api/Actas/mesa/{mesaId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasMesaMesaIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasMesaMesaIdGet$Plain$Response(params: ApiActasMesaMesaIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDto>> {
    const obs = apiActasMesaMesaIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasMesaMesaIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasMesaMesaIdGet$Plain(params: ApiActasMesaMesaIdGet$Plain$Params, context?: HttpContext): Promise<ActaDto> {
    const resp = this.apiActasMesaMesaIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDto>): ActaDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasMesaMesaIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasMesaMesaIdGet$Json$Response(params: ApiActasMesaMesaIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaDto>> {
    const obs = apiActasMesaMesaIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasMesaMesaIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasMesaMesaIdGet$Json(params: ApiActasMesaMesaIdGet$Json$Params, context?: HttpContext): Promise<ActaDto> {
    const resp = this.apiActasMesaMesaIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaDto>): ActaDto => r.body);
  }

  /** Path part for operation `apiActasPost()` */
  static readonly ApiActasPostPath = '/api/Actas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasPost$Plain$Response(params?: ApiActasPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaEleccion>> {
    const obs = apiActasPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasPost$Plain(params?: ApiActasPost$Plain$Params, context?: HttpContext): Promise<ActaEleccion> {
    const resp = this.apiActasPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaEleccion>): ActaEleccion => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasPost$Json$Response(params?: ApiActasPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ActaEleccion>> {
    const obs = apiActasPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiActasPost$Json(params?: ApiActasPost$Json$Params, context?: HttpContext): Promise<ActaEleccion> {
    const resp = this.apiActasPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActaEleccion>): ActaEleccion => r.body);
  }

  /** Path part for operation `apiActasCambiarEstadoIdPut()` */
  static readonly ApiActasCambiarEstadoIdPutPath = '/api/Actas/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiActasCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasCambiarEstadoIdPut$Response(params: ApiActasCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiActasCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiActasCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiActasCambiarEstadoIdPut(params: ApiActasCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiActasCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
