/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiBitacoraIdGet$Json } from '../fn/bitacora/api-bitacora-id-get-json';
import { ApiBitacoraIdGet$Json$Params } from '../fn/bitacora/api-bitacora-id-get-json';
import { apiBitacoraIdGet$Plain } from '../fn/bitacora/api-bitacora-id-get-plain';
import { ApiBitacoraIdGet$Plain$Params } from '../fn/bitacora/api-bitacora-id-get-plain';
import { apiBitacoraPaginacionGet$Json } from '../fn/bitacora/api-bitacora-paginacion-get-json';
import { ApiBitacoraPaginacionGet$Json$Params } from '../fn/bitacora/api-bitacora-paginacion-get-json';
import { apiBitacoraPaginacionGet$Plain } from '../fn/bitacora/api-bitacora-paginacion-get-plain';
import { ApiBitacoraPaginacionGet$Plain$Params } from '../fn/bitacora/api-bitacora-paginacion-get-plain';
import { apiBitacoraRegistroGet$Json } from '../fn/bitacora/api-bitacora-registro-get-json';
import { ApiBitacoraRegistroGet$Json$Params } from '../fn/bitacora/api-bitacora-registro-get-json';
import { apiBitacoraRegistroGet$Plain } from '../fn/bitacora/api-bitacora-registro-get-plain';
import { ApiBitacoraRegistroGet$Plain$Params } from '../fn/bitacora/api-bitacora-registro-get-plain';
import { BitacoraDto } from '../models/bitacora-dto';
import { BitacoraDtoPaginacionDto } from '../models/bitacora-dto-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class BitacoraService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiBitacoraPaginacionGet()` */
  static readonly ApiBitacoraPaginacionGetPath = '/api/Bitacora/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraPaginacionGet$Plain$Response(params?: ApiBitacoraPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<BitacoraDtoPaginacionDto>> {
    const obs = apiBitacoraPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraPaginacionGet$Plain(params?: ApiBitacoraPaginacionGet$Plain$Params, context?: HttpContext): Promise<BitacoraDtoPaginacionDto> {
    const resp = this.apiBitacoraPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<BitacoraDtoPaginacionDto>): BitacoraDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraPaginacionGet$Json$Response(params?: ApiBitacoraPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<BitacoraDtoPaginacionDto>> {
    const obs = apiBitacoraPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraPaginacionGet$Json(params?: ApiBitacoraPaginacionGet$Json$Params, context?: HttpContext): Promise<BitacoraDtoPaginacionDto> {
    const resp = this.apiBitacoraPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<BitacoraDtoPaginacionDto>): BitacoraDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiBitacoraIdGet()` */
  static readonly ApiBitacoraIdGetPath = '/api/Bitacora/id';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraIdGet$Plain$Response(params?: ApiBitacoraIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<BitacoraDto>> {
    const obs = apiBitacoraIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraIdGet$Plain(params?: ApiBitacoraIdGet$Plain$Params, context?: HttpContext): Promise<BitacoraDto> {
    const resp = this.apiBitacoraIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<BitacoraDto>): BitacoraDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraIdGet$Json$Response(params?: ApiBitacoraIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<BitacoraDto>> {
    const obs = apiBitacoraIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraIdGet$Json(params?: ApiBitacoraIdGet$Json$Params, context?: HttpContext): Promise<BitacoraDto> {
    const resp = this.apiBitacoraIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<BitacoraDto>): BitacoraDto => r.body);
  }

  /** Path part for operation `apiBitacoraRegistroGet()` */
  static readonly ApiBitacoraRegistroGetPath = '/api/Bitacora/registro';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraRegistroGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraRegistroGet$Plain$Response(params?: ApiBitacoraRegistroGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BitacoraDto>>> {
    const obs = apiBitacoraRegistroGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraRegistroGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraRegistroGet$Plain(params?: ApiBitacoraRegistroGet$Plain$Params, context?: HttpContext): Promise<Array<BitacoraDto>> {
    const resp = this.apiBitacoraRegistroGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BitacoraDto>>): Array<BitacoraDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiBitacoraRegistroGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraRegistroGet$Json$Response(params?: ApiBitacoraRegistroGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BitacoraDto>>> {
    const obs = apiBitacoraRegistroGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiBitacoraRegistroGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiBitacoraRegistroGet$Json(params?: ApiBitacoraRegistroGet$Json$Params, context?: HttpContext): Promise<Array<BitacoraDto>> {
    const resp = this.apiBitacoraRegistroGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BitacoraDto>>): Array<BitacoraDto> => r.body);
  }

}
