/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCandidatosCambiarEstadoIdPut } from '../fn/candidatos/api-candidatos-cambiar-estado-id-put';
import { ApiCandidatosCambiarEstadoIdPut$Params } from '../fn/candidatos/api-candidatos-cambiar-estado-id-put';
import { apiCandidatosIdGet$Json } from '../fn/candidatos/api-candidatos-id-get-json';
import { ApiCandidatosIdGet$Json$Params } from '../fn/candidatos/api-candidatos-id-get-json';
import { apiCandidatosIdGet$Plain } from '../fn/candidatos/api-candidatos-id-get-plain';
import { ApiCandidatosIdGet$Plain$Params } from '../fn/candidatos/api-candidatos-id-get-plain';
import { apiCandidatosIdPut } from '../fn/candidatos/api-candidatos-id-put';
import { ApiCandidatosIdPut$Params } from '../fn/candidatos/api-candidatos-id-put';
import { apiCandidatosPaginacionGet$Json } from '../fn/candidatos/api-candidatos-paginacion-get-json';
import { ApiCandidatosPaginacionGet$Json$Params } from '../fn/candidatos/api-candidatos-paginacion-get-json';
import { apiCandidatosPaginacionGet$Plain } from '../fn/candidatos/api-candidatos-paginacion-get-plain';
import { ApiCandidatosPaginacionGet$Plain$Params } from '../fn/candidatos/api-candidatos-paginacion-get-plain';
import { apiCandidatosPost$Json } from '../fn/candidatos/api-candidatos-post-json';
import { ApiCandidatosPost$Json$Params } from '../fn/candidatos/api-candidatos-post-json';
import { apiCandidatosPost$Plain } from '../fn/candidatos/api-candidatos-post-plain';
import { ApiCandidatosPost$Plain$Params } from '../fn/candidatos/api-candidatos-post-plain';
import { Candidato } from '../models/candidato';
import { CandidatoDto } from '../models/candidato-dto';
import { CandidatoDtoPaginacionDto } from '../models/candidato-dto-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class CandidatosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCandidatosPaginacionGet()` */
  static readonly ApiCandidatosPaginacionGetPath = '/api/Candidatos/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosPaginacionGet$Plain$Response(params?: ApiCandidatosPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<CandidatoDtoPaginacionDto>> {
    const obs = apiCandidatosPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosPaginacionGet$Plain(params?: ApiCandidatosPaginacionGet$Plain$Params, context?: HttpContext): Promise<CandidatoDtoPaginacionDto> {
    const resp = this.apiCandidatosPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<CandidatoDtoPaginacionDto>): CandidatoDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosPaginacionGet$Json$Response(params?: ApiCandidatosPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<CandidatoDtoPaginacionDto>> {
    const obs = apiCandidatosPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosPaginacionGet$Json(params?: ApiCandidatosPaginacionGet$Json$Params, context?: HttpContext): Promise<CandidatoDtoPaginacionDto> {
    const resp = this.apiCandidatosPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<CandidatoDtoPaginacionDto>): CandidatoDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiCandidatosIdGet()` */
  static readonly ApiCandidatosIdGetPath = '/api/Candidatos/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosIdGet$Plain$Response(params: ApiCandidatosIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<CandidatoDto>> {
    const obs = apiCandidatosIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosIdGet$Plain(params: ApiCandidatosIdGet$Plain$Params, context?: HttpContext): Promise<CandidatoDto> {
    const resp = this.apiCandidatosIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<CandidatoDto>): CandidatoDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosIdGet$Json$Response(params: ApiCandidatosIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<CandidatoDto>> {
    const obs = apiCandidatosIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosIdGet$Json(params: ApiCandidatosIdGet$Json$Params, context?: HttpContext): Promise<CandidatoDto> {
    const resp = this.apiCandidatosIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<CandidatoDto>): CandidatoDto => r.body);
  }

  /** Path part for operation `apiCandidatosIdPut()` */
  static readonly ApiCandidatosIdPutPath = '/api/Candidatos/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosIdPut$Response(params: ApiCandidatosIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiCandidatosIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosIdPut(params: ApiCandidatosIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiCandidatosIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiCandidatosPost()` */
  static readonly ApiCandidatosPostPath = '/api/Candidatos';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosPost$Plain$Response(params?: ApiCandidatosPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Candidato>> {
    const obs = apiCandidatosPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosPost$Plain(params?: ApiCandidatosPost$Plain$Params, context?: HttpContext): Promise<Candidato> {
    const resp = this.apiCandidatosPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Candidato>): Candidato => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosPost$Json$Response(params?: ApiCandidatosPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Candidato>> {
    const obs = apiCandidatosPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCandidatosPost$Json(params?: ApiCandidatosPost$Json$Params, context?: HttpContext): Promise<Candidato> {
    const resp = this.apiCandidatosPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Candidato>): Candidato => r.body);
  }

  /** Path part for operation `apiCandidatosCambiarEstadoIdPut()` */
  static readonly ApiCandidatosCambiarEstadoIdPutPath = '/api/Candidatos/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCandidatosCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosCambiarEstadoIdPut$Response(params: ApiCandidatosCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiCandidatosCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCandidatosCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCandidatosCambiarEstadoIdPut(params: ApiCandidatosCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiCandidatosCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
