/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEleccionesGet$Json } from '../fn/elecciones/api-elecciones-get-json';
import { ApiEleccionesGet$Json$Params } from '../fn/elecciones/api-elecciones-get-json';
import { apiEleccionesGet$Plain } from '../fn/elecciones/api-elecciones-get-plain';
import { ApiEleccionesGet$Plain$Params } from '../fn/elecciones/api-elecciones-get-plain';
import { apiEleccionesIdGet$Json } from '../fn/elecciones/api-elecciones-id-get-json';
import { ApiEleccionesIdGet$Json$Params } from '../fn/elecciones/api-elecciones-id-get-json';
import { apiEleccionesIdGet$Plain } from '../fn/elecciones/api-elecciones-id-get-plain';
import { ApiEleccionesIdGet$Plain$Params } from '../fn/elecciones/api-elecciones-id-get-plain';
import { apiEleccionesIdPut } from '../fn/elecciones/api-elecciones-id-put';
import { ApiEleccionesIdPut$Params } from '../fn/elecciones/api-elecciones-id-put';
import { apiEleccionesPost$Json } from '../fn/elecciones/api-elecciones-post-json';
import { ApiEleccionesPost$Json$Params } from '../fn/elecciones/api-elecciones-post-json';
import { apiEleccionesPost$Plain } from '../fn/elecciones/api-elecciones-post-plain';
import { ApiEleccionesPost$Plain$Params } from '../fn/elecciones/api-elecciones-post-plain';
import { Eleccion } from '../models/eleccion';

@Injectable({ providedIn: 'root' })
export class EleccionesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEleccionesGet()` */
  static readonly ApiEleccionesGetPath = '/api/Elecciones';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesGet$Plain$Response(params?: ApiEleccionesGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Eleccion>>> {
    const obs = apiEleccionesGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesGet$Plain(params?: ApiEleccionesGet$Plain$Params, context?: HttpContext): Promise<Array<Eleccion>> {
    const resp = this.apiEleccionesGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Eleccion>>): Array<Eleccion> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesGet$Json$Response(params?: ApiEleccionesGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Eleccion>>> {
    const obs = apiEleccionesGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesGet$Json(params?: ApiEleccionesGet$Json$Params, context?: HttpContext): Promise<Array<Eleccion>> {
    const resp = this.apiEleccionesGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Eleccion>>): Array<Eleccion> => r.body);
  }

  /** Path part for operation `apiEleccionesPost()` */
  static readonly ApiEleccionesPostPath = '/api/Elecciones';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesPost$Plain$Response(params?: ApiEleccionesPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Eleccion>> {
    const obs = apiEleccionesPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesPost$Plain(params?: ApiEleccionesPost$Plain$Params, context?: HttpContext): Promise<Eleccion> {
    const resp = this.apiEleccionesPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Eleccion>): Eleccion => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesPost$Json$Response(params?: ApiEleccionesPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Eleccion>> {
    const obs = apiEleccionesPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesPost$Json(params?: ApiEleccionesPost$Json$Params, context?: HttpContext): Promise<Eleccion> {
    const resp = this.apiEleccionesPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Eleccion>): Eleccion => r.body);
  }

  /** Path part for operation `apiEleccionesIdGet()` */
  static readonly ApiEleccionesIdGetPath = '/api/Elecciones/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesIdGet$Plain$Response(params: ApiEleccionesIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Eleccion>> {
    const obs = apiEleccionesIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesIdGet$Plain(params: ApiEleccionesIdGet$Plain$Params, context?: HttpContext): Promise<Eleccion> {
    const resp = this.apiEleccionesIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Eleccion>): Eleccion => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesIdGet$Json$Response(params: ApiEleccionesIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Eleccion>> {
    const obs = apiEleccionesIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEleccionesIdGet$Json(params: ApiEleccionesIdGet$Json$Params, context?: HttpContext): Promise<Eleccion> {
    const resp = this.apiEleccionesIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Eleccion>): Eleccion => r.body);
  }

  /** Path part for operation `apiEleccionesIdPut()` */
  static readonly ApiEleccionesIdPutPath = '/api/Elecciones/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEleccionesIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesIdPut$Response(params: ApiEleccionesIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiEleccionesIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEleccionesIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEleccionesIdPut(params: ApiEleccionesIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiEleccionesIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
