/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiListasElectoralCambiarEstadoIdPut } from '../fn/listas-electoral/api-listas-electoral-cambiar-estado-id-put';
import { ApiListasElectoralCambiarEstadoIdPut$Params } from '../fn/listas-electoral/api-listas-electoral-cambiar-estado-id-put';
import { apiListasElectoralIdGet$Json } from '../fn/listas-electoral/api-listas-electoral-id-get-json';
import { ApiListasElectoralIdGet$Json$Params } from '../fn/listas-electoral/api-listas-electoral-id-get-json';
import { apiListasElectoralIdGet$Plain } from '../fn/listas-electoral/api-listas-electoral-id-get-plain';
import { ApiListasElectoralIdGet$Plain$Params } from '../fn/listas-electoral/api-listas-electoral-id-get-plain';
import { apiListasElectoralIdPut } from '../fn/listas-electoral/api-listas-electoral-id-put';
import { ApiListasElectoralIdPut$Params } from '../fn/listas-electoral/api-listas-electoral-id-put';
import { apiListasElectoralPaginacionGet$Json } from '../fn/listas-electoral/api-listas-electoral-paginacion-get-json';
import { ApiListasElectoralPaginacionGet$Json$Params } from '../fn/listas-electoral/api-listas-electoral-paginacion-get-json';
import { apiListasElectoralPaginacionGet$Plain } from '../fn/listas-electoral/api-listas-electoral-paginacion-get-plain';
import { ApiListasElectoralPaginacionGet$Plain$Params } from '../fn/listas-electoral/api-listas-electoral-paginacion-get-plain';
import { apiListasElectoralPost$Json } from '../fn/listas-electoral/api-listas-electoral-post-json';
import { ApiListasElectoralPost$Json$Params } from '../fn/listas-electoral/api-listas-electoral-post-json';
import { apiListasElectoralPost$Plain } from '../fn/listas-electoral/api-listas-electoral-post-plain';
import { ApiListasElectoralPost$Plain$Params } from '../fn/listas-electoral/api-listas-electoral-post-plain';
import { ListaElectoral } from '../models/lista-electoral';
import { ListaElectoralPaginacionDto } from '../models/lista-electoral-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class ListasElectoralService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiListasElectoralPaginacionGet()` */
  static readonly ApiListasElectoralPaginacionGetPath = '/api/ListasElectoral/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralPaginacionGet$Plain$Response(params?: ApiListasElectoralPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoralPaginacionDto>> {
    const obs = apiListasElectoralPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralPaginacionGet$Plain(params?: ApiListasElectoralPaginacionGet$Plain$Params, context?: HttpContext): Promise<ListaElectoralPaginacionDto> {
    const resp = this.apiListasElectoralPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoralPaginacionDto>): ListaElectoralPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralPaginacionGet$Json$Response(params?: ApiListasElectoralPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoralPaginacionDto>> {
    const obs = apiListasElectoralPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralPaginacionGet$Json(params?: ApiListasElectoralPaginacionGet$Json$Params, context?: HttpContext): Promise<ListaElectoralPaginacionDto> {
    const resp = this.apiListasElectoralPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoralPaginacionDto>): ListaElectoralPaginacionDto => r.body);
  }

  /** Path part for operation `apiListasElectoralIdGet()` */
  static readonly ApiListasElectoralIdGetPath = '/api/ListasElectoral/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralIdGet$Plain$Response(params: ApiListasElectoralIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoral>> {
    const obs = apiListasElectoralIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralIdGet$Plain(params: ApiListasElectoralIdGet$Plain$Params, context?: HttpContext): Promise<ListaElectoral> {
    const resp = this.apiListasElectoralIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoral>): ListaElectoral => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralIdGet$Json$Response(params: ApiListasElectoralIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoral>> {
    const obs = apiListasElectoralIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralIdGet$Json(params: ApiListasElectoralIdGet$Json$Params, context?: HttpContext): Promise<ListaElectoral> {
    const resp = this.apiListasElectoralIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoral>): ListaElectoral => r.body);
  }

  /** Path part for operation `apiListasElectoralIdPut()` */
  static readonly ApiListasElectoralIdPutPath = '/api/ListasElectoral/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralIdPut$Response(params: ApiListasElectoralIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiListasElectoralIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralIdPut(params: ApiListasElectoralIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiListasElectoralIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiListasElectoralPost()` */
  static readonly ApiListasElectoralPostPath = '/api/ListasElectoral';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralPost$Plain$Response(params?: ApiListasElectoralPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoral>> {
    const obs = apiListasElectoralPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralPost$Plain(params?: ApiListasElectoralPost$Plain$Params, context?: HttpContext): Promise<ListaElectoral> {
    const resp = this.apiListasElectoralPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoral>): ListaElectoral => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralPost$Json$Response(params?: ApiListasElectoralPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ListaElectoral>> {
    const obs = apiListasElectoralPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiListasElectoralPost$Json(params?: ApiListasElectoralPost$Json$Params, context?: HttpContext): Promise<ListaElectoral> {
    const resp = this.apiListasElectoralPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ListaElectoral>): ListaElectoral => r.body);
  }

  /** Path part for operation `apiListasElectoralCambiarEstadoIdPut()` */
  static readonly ApiListasElectoralCambiarEstadoIdPutPath = '/api/ListasElectoral/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiListasElectoralCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralCambiarEstadoIdPut$Response(params: ApiListasElectoralCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiListasElectoralCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiListasElectoralCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiListasElectoralCambiarEstadoIdPut(params: ApiListasElectoralCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiListasElectoralCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
