/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiMesasElectoralCambiarEstadoIdPut } from '../fn/mesas-electoral/api-mesas-electoral-cambiar-estado-id-put';
import { ApiMesasElectoralCambiarEstadoIdPut$Params } from '../fn/mesas-electoral/api-mesas-electoral-cambiar-estado-id-put';
import { apiMesasElectoralCodigoMesaGet } from '../fn/mesas-electoral/api-mesas-electoral-codigo-mesa-get';
import { ApiMesasElectoralCodigoMesaGet$Params } from '../fn/mesas-electoral/api-mesas-electoral-codigo-mesa-get';
import { apiMesasElectoralDisponiblePorZonaGet$Json } from '../fn/mesas-electoral/api-mesas-electoral-disponible-por-zona-get-json';
import { ApiMesasElectoralDisponiblePorZonaGet$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-disponible-por-zona-get-json';
import { apiMesasElectoralDisponiblePorZonaGet$Plain } from '../fn/mesas-electoral/api-mesas-electoral-disponible-por-zona-get-plain';
import { ApiMesasElectoralDisponiblePorZonaGet$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-disponible-por-zona-get-plain';
import { apiMesasElectoralIdGet$Json } from '../fn/mesas-electoral/api-mesas-electoral-id-get-json';
import { ApiMesasElectoralIdGet$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-id-get-json';
import { apiMesasElectoralIdGet$Plain } from '../fn/mesas-electoral/api-mesas-electoral-id-get-plain';
import { ApiMesasElectoralIdGet$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-id-get-plain';
import { apiMesasElectoralIdPut } from '../fn/mesas-electoral/api-mesas-electoral-id-put';
import { ApiMesasElectoralIdPut$Params } from '../fn/mesas-electoral/api-mesas-electoral-id-put';
import { apiMesasElectoralLotePost$Json } from '../fn/mesas-electoral/api-mesas-electoral-lote-post-json';
import { ApiMesasElectoralLotePost$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-lote-post-json';
import { apiMesasElectoralLotePost$Plain } from '../fn/mesas-electoral/api-mesas-electoral-lote-post-plain';
import { ApiMesasElectoralLotePost$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-lote-post-plain';
import { apiMesasElectoralPaginacionGet$Json } from '../fn/mesas-electoral/api-mesas-electoral-paginacion-get-json';
import { ApiMesasElectoralPaginacionGet$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-paginacion-get-json';
import { apiMesasElectoralPaginacionGet$Plain } from '../fn/mesas-electoral/api-mesas-electoral-paginacion-get-plain';
import { ApiMesasElectoralPaginacionGet$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-paginacion-get-plain';
import { apiMesasElectoralPost$Json } from '../fn/mesas-electoral/api-mesas-electoral-post-json';
import { ApiMesasElectoralPost$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-post-json';
import { apiMesasElectoralPost$Plain } from '../fn/mesas-electoral/api-mesas-electoral-post-plain';
import { ApiMesasElectoralPost$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-post-plain';
import { apiMesasElectoralZonaGet$Json } from '../fn/mesas-electoral/api-mesas-electoral-zona-get-json';
import { ApiMesasElectoralZonaGet$Json$Params } from '../fn/mesas-electoral/api-mesas-electoral-zona-get-json';
import { apiMesasElectoralZonaGet$Plain } from '../fn/mesas-electoral/api-mesas-electoral-zona-get-plain';
import { ApiMesasElectoralZonaGet$Plain$Params } from '../fn/mesas-electoral/api-mesas-electoral-zona-get-plain';
import { MesaElectoral } from '../models/mesa-electoral';
import { MesaElectoralDto } from '../models/mesa-electoral-dto';
import { MesaElectoralDtoPaginacionDto } from '../models/mesa-electoral-dto-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class MesasElectoralService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiMesasElectoralPaginacionGet()` */
  static readonly ApiMesasElectoralPaginacionGetPath = '/api/MesasElectoral/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralPaginacionGet$Plain$Response(params?: ApiMesasElectoralPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoralDtoPaginacionDto>> {
    const obs = apiMesasElectoralPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralPaginacionGet$Plain(params?: ApiMesasElectoralPaginacionGet$Plain$Params, context?: HttpContext): Promise<MesaElectoralDtoPaginacionDto> {
    const resp = this.apiMesasElectoralPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoralDtoPaginacionDto>): MesaElectoralDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralPaginacionGet$Json$Response(params?: ApiMesasElectoralPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoralDtoPaginacionDto>> {
    const obs = apiMesasElectoralPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralPaginacionGet$Json(params?: ApiMesasElectoralPaginacionGet$Json$Params, context?: HttpContext): Promise<MesaElectoralDtoPaginacionDto> {
    const resp = this.apiMesasElectoralPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoralDtoPaginacionDto>): MesaElectoralDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiMesasElectoralIdGet()` */
  static readonly ApiMesasElectoralIdGetPath = '/api/MesasElectoral/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralIdGet$Plain$Response(params: ApiMesasElectoralIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoralDto>> {
    const obs = apiMesasElectoralIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralIdGet$Plain(params: ApiMesasElectoralIdGet$Plain$Params, context?: HttpContext): Promise<MesaElectoralDto> {
    const resp = this.apiMesasElectoralIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoralDto>): MesaElectoralDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralIdGet$Json$Response(params: ApiMesasElectoralIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoralDto>> {
    const obs = apiMesasElectoralIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralIdGet$Json(params: ApiMesasElectoralIdGet$Json$Params, context?: HttpContext): Promise<MesaElectoralDto> {
    const resp = this.apiMesasElectoralIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoralDto>): MesaElectoralDto => r.body);
  }

  /** Path part for operation `apiMesasElectoralIdPut()` */
  static readonly ApiMesasElectoralIdPutPath = '/api/MesasElectoral/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralIdPut$Response(params: ApiMesasElectoralIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiMesasElectoralIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralIdPut(params: ApiMesasElectoralIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiMesasElectoralIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiMesasElectoralZonaGet()` */
  static readonly ApiMesasElectoralZonaGetPath = '/api/MesasElectoral/zona';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralZonaGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralZonaGet$Plain$Response(params?: ApiMesasElectoralZonaGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<MesaElectoralDto>>> {
    const obs = apiMesasElectoralZonaGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralZonaGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralZonaGet$Plain(params?: ApiMesasElectoralZonaGet$Plain$Params, context?: HttpContext): Promise<Array<MesaElectoralDto>> {
    const resp = this.apiMesasElectoralZonaGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<MesaElectoralDto>>): Array<MesaElectoralDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralZonaGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralZonaGet$Json$Response(params?: ApiMesasElectoralZonaGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<MesaElectoralDto>>> {
    const obs = apiMesasElectoralZonaGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralZonaGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralZonaGet$Json(params?: ApiMesasElectoralZonaGet$Json$Params, context?: HttpContext): Promise<Array<MesaElectoralDto>> {
    const resp = this.apiMesasElectoralZonaGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<MesaElectoralDto>>): Array<MesaElectoralDto> => r.body);
  }

  /** Path part for operation `apiMesasElectoralDisponiblePorZonaGet()` */
  static readonly ApiMesasElectoralDisponiblePorZonaGetPath = '/api/MesasElectoral/disponible-por-zona';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralDisponiblePorZonaGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralDisponiblePorZonaGet$Plain$Response(params?: ApiMesasElectoralDisponiblePorZonaGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<MesaElectoralDto>>> {
    const obs = apiMesasElectoralDisponiblePorZonaGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralDisponiblePorZonaGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralDisponiblePorZonaGet$Plain(params?: ApiMesasElectoralDisponiblePorZonaGet$Plain$Params, context?: HttpContext): Promise<Array<MesaElectoralDto>> {
    const resp = this.apiMesasElectoralDisponiblePorZonaGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<MesaElectoralDto>>): Array<MesaElectoralDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralDisponiblePorZonaGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralDisponiblePorZonaGet$Json$Response(params?: ApiMesasElectoralDisponiblePorZonaGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<MesaElectoralDto>>> {
    const obs = apiMesasElectoralDisponiblePorZonaGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralDisponiblePorZonaGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralDisponiblePorZonaGet$Json(params?: ApiMesasElectoralDisponiblePorZonaGet$Json$Params, context?: HttpContext): Promise<Array<MesaElectoralDto>> {
    const resp = this.apiMesasElectoralDisponiblePorZonaGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<MesaElectoralDto>>): Array<MesaElectoralDto> => r.body);
  }

  /** Path part for operation `apiMesasElectoralCodigoMesaGet()` */
  static readonly ApiMesasElectoralCodigoMesaGetPath = '/api/MesasElectoral/codigo-mesa';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralCodigoMesaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralCodigoMesaGet$Response(params?: ApiMesasElectoralCodigoMesaGet$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiMesasElectoralCodigoMesaGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralCodigoMesaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralCodigoMesaGet(params?: ApiMesasElectoralCodigoMesaGet$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiMesasElectoralCodigoMesaGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiMesasElectoralPost()` */
  static readonly ApiMesasElectoralPostPath = '/api/MesasElectoral';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralPost$Plain$Response(params?: ApiMesasElectoralPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoral>> {
    const obs = apiMesasElectoralPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralPost$Plain(params?: ApiMesasElectoralPost$Plain$Params, context?: HttpContext): Promise<MesaElectoral> {
    const resp = this.apiMesasElectoralPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoral>): MesaElectoral => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralPost$Json$Response(params?: ApiMesasElectoralPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoral>> {
    const obs = apiMesasElectoralPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMesasElectoralPost$Json(params?: ApiMesasElectoralPost$Json$Params, context?: HttpContext): Promise<MesaElectoral> {
    const resp = this.apiMesasElectoralPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoral>): MesaElectoral => r.body);
  }

  /** Path part for operation `apiMesasElectoralLotePost()` */
  static readonly ApiMesasElectoralLotePostPath = '/api/MesasElectoral/lote';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralLotePost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralLotePost$Plain$Response(params?: ApiMesasElectoralLotePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoral>> {
    const obs = apiMesasElectoralLotePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralLotePost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralLotePost$Plain(params?: ApiMesasElectoralLotePost$Plain$Params, context?: HttpContext): Promise<MesaElectoral> {
    const resp = this.apiMesasElectoralLotePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoral>): MesaElectoral => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralLotePost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralLotePost$Json$Response(params?: ApiMesasElectoralLotePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<MesaElectoral>> {
    const obs = apiMesasElectoralLotePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralLotePost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralLotePost$Json(params?: ApiMesasElectoralLotePost$Json$Params, context?: HttpContext): Promise<MesaElectoral> {
    const resp = this.apiMesasElectoralLotePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<MesaElectoral>): MesaElectoral => r.body);
  }

  /** Path part for operation `apiMesasElectoralCambiarEstadoIdPut()` */
  static readonly ApiMesasElectoralCambiarEstadoIdPutPath = '/api/MesasElectoral/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMesasElectoralCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralCambiarEstadoIdPut$Response(params: ApiMesasElectoralCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiMesasElectoralCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMesasElectoralCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMesasElectoralCambiarEstadoIdPut(params: ApiMesasElectoralCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiMesasElectoralCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
