/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiResultadosEleccionCantonGet$Json } from '../fn/resultados/api-resultados-eleccion-canton-get-json';
import { ApiResultadosEleccionCantonGet$Json$Params } from '../fn/resultados/api-resultados-eleccion-canton-get-json';
import { apiResultadosEleccionCantonGet$Plain } from '../fn/resultados/api-resultados-eleccion-canton-get-plain';
import { ApiResultadosEleccionCantonGet$Plain$Params } from '../fn/resultados/api-resultados-eleccion-canton-get-plain';
import { apiResultadosEleccionGet$Json } from '../fn/resultados/api-resultados-eleccion-get-json';
import { ApiResultadosEleccionGet$Json$Params } from '../fn/resultados/api-resultados-eleccion-get-json';
import { apiResultadosEleccionGet$Plain } from '../fn/resultados/api-resultados-eleccion-get-plain';
import { ApiResultadosEleccionGet$Plain$Params } from '../fn/resultados/api-resultados-eleccion-get-plain';
import { apiResultadosEleccionParroquiaGet$Json } from '../fn/resultados/api-resultados-eleccion-parroquia-get-json';
import { ApiResultadosEleccionParroquiaGet$Json$Params } from '../fn/resultados/api-resultados-eleccion-parroquia-get-json';
import { apiResultadosEleccionParroquiaGet$Plain } from '../fn/resultados/api-resultados-eleccion-parroquia-get-plain';
import { ApiResultadosEleccionParroquiaGet$Plain$Params } from '../fn/resultados/api-resultados-eleccion-parroquia-get-plain';
import { apiResultadosEleccionZonaGet$Json } from '../fn/resultados/api-resultados-eleccion-zona-get-json';
import { ApiResultadosEleccionZonaGet$Json$Params } from '../fn/resultados/api-resultados-eleccion-zona-get-json';
import { apiResultadosEleccionZonaGet$Plain } from '../fn/resultados/api-resultados-eleccion-zona-get-plain';
import { ApiResultadosEleccionZonaGet$Plain$Params } from '../fn/resultados/api-resultados-eleccion-zona-get-plain';
import { ResultadoEleccionDto } from '../models/resultado-eleccion-dto';

@Injectable({ providedIn: 'root' })
export class ResultadosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiResultadosEleccionGet()` */
  static readonly ApiResultadosEleccionGetPath = '/api/Resultados/eleccion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionGet$Plain$Response(params?: ApiResultadosEleccionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionGet$Plain(params?: ApiResultadosEleccionGet$Plain$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionGet$Json$Response(params?: ApiResultadosEleccionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionGet$Json(params?: ApiResultadosEleccionGet$Json$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /** Path part for operation `apiResultadosEleccionCantonGet()` */
  static readonly ApiResultadosEleccionCantonGetPath = '/api/Resultados/eleccion/canton';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionCantonGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionCantonGet$Plain$Response(params?: ApiResultadosEleccionCantonGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionCantonGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionCantonGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionCantonGet$Plain(params?: ApiResultadosEleccionCantonGet$Plain$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionCantonGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionCantonGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionCantonGet$Json$Response(params?: ApiResultadosEleccionCantonGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionCantonGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionCantonGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionCantonGet$Json(params?: ApiResultadosEleccionCantonGet$Json$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionCantonGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /** Path part for operation `apiResultadosEleccionParroquiaGet()` */
  static readonly ApiResultadosEleccionParroquiaGetPath = '/api/Resultados/eleccion/parroquia';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionParroquiaGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionParroquiaGet$Plain$Response(params?: ApiResultadosEleccionParroquiaGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionParroquiaGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionParroquiaGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionParroquiaGet$Plain(params?: ApiResultadosEleccionParroquiaGet$Plain$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionParroquiaGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionParroquiaGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionParroquiaGet$Json$Response(params?: ApiResultadosEleccionParroquiaGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionParroquiaGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionParroquiaGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionParroquiaGet$Json(params?: ApiResultadosEleccionParroquiaGet$Json$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionParroquiaGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /** Path part for operation `apiResultadosEleccionZonaGet()` */
  static readonly ApiResultadosEleccionZonaGetPath = '/api/Resultados/eleccion/zona';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionZonaGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionZonaGet$Plain$Response(params?: ApiResultadosEleccionZonaGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionZonaGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionZonaGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionZonaGet$Plain(params?: ApiResultadosEleccionZonaGet$Plain$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionZonaGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiResultadosEleccionZonaGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionZonaGet$Json$Response(params?: ApiResultadosEleccionZonaGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoEleccionDto>> {
    const obs = apiResultadosEleccionZonaGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiResultadosEleccionZonaGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiResultadosEleccionZonaGet$Json(params?: ApiResultadosEleccionZonaGet$Json$Params, context?: HttpContext): Promise<ResultadoEleccionDto> {
    const resp = this.apiResultadosEleccionZonaGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoEleccionDto>): ResultadoEleccionDto => r.body);
  }

}
