/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiRolesCambiarEstadoIdPut } from '../fn/roles/api-roles-cambiar-estado-id-put';
import { ApiRolesCambiarEstadoIdPut$Params } from '../fn/roles/api-roles-cambiar-estado-id-put';
import { apiRolesIdGet$Json } from '../fn/roles/api-roles-id-get-json';
import { ApiRolesIdGet$Json$Params } from '../fn/roles/api-roles-id-get-json';
import { apiRolesIdGet$Plain } from '../fn/roles/api-roles-id-get-plain';
import { ApiRolesIdGet$Plain$Params } from '../fn/roles/api-roles-id-get-plain';
import { apiRolesIdPut } from '../fn/roles/api-roles-id-put';
import { ApiRolesIdPut$Params } from '../fn/roles/api-roles-id-put';
import { apiRolesPaginacionGet$Json } from '../fn/roles/api-roles-paginacion-get-json';
import { ApiRolesPaginacionGet$Json$Params } from '../fn/roles/api-roles-paginacion-get-json';
import { apiRolesPaginacionGet$Plain } from '../fn/roles/api-roles-paginacion-get-plain';
import { ApiRolesPaginacionGet$Plain$Params } from '../fn/roles/api-roles-paginacion-get-plain';
import { apiRolesPost$Json } from '../fn/roles/api-roles-post-json';
import { ApiRolesPost$Json$Params } from '../fn/roles/api-roles-post-json';
import { apiRolesPost$Plain } from '../fn/roles/api-roles-post-plain';
import { ApiRolesPost$Plain$Params } from '../fn/roles/api-roles-post-plain';
import { RolDto } from '../models/rol-dto';
import { RolDtoPaginacionDto } from '../models/rol-dto-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class RolesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiRolesPaginacionGet()` */
  static readonly ApiRolesPaginacionGetPath = '/api/Roles/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesPaginacionGet$Plain$Response(params?: ApiRolesPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDtoPaginacionDto>> {
    const obs = apiRolesPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesPaginacionGet$Plain(params?: ApiRolesPaginacionGet$Plain$Params, context?: HttpContext): Promise<RolDtoPaginacionDto> {
    const resp = this.apiRolesPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDtoPaginacionDto>): RolDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesPaginacionGet$Json$Response(params?: ApiRolesPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDtoPaginacionDto>> {
    const obs = apiRolesPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesPaginacionGet$Json(params?: ApiRolesPaginacionGet$Json$Params, context?: HttpContext): Promise<RolDtoPaginacionDto> {
    const resp = this.apiRolesPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDtoPaginacionDto>): RolDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiRolesIdGet()` */
  static readonly ApiRolesIdGetPath = '/api/Roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Plain$Response(params: ApiRolesIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDto>> {
    const obs = apiRolesIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Plain(params: ApiRolesIdGet$Plain$Params, context?: HttpContext): Promise<RolDto> {
    const resp = this.apiRolesIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDto>): RolDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Json$Response(params: ApiRolesIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDto>> {
    const obs = apiRolesIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesIdGet$Json(params: ApiRolesIdGet$Json$Params, context?: HttpContext): Promise<RolDto> {
    const resp = this.apiRolesIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDto>): RolDto => r.body);
  }

  /** Path part for operation `apiRolesIdPut()` */
  static readonly ApiRolesIdPutPath = '/api/Roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesIdPut$Response(params: ApiRolesIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiRolesIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesIdPut(params: ApiRolesIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiRolesIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiRolesPost()` */
  static readonly ApiRolesPostPath = '/api/Roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesPost$Plain$Response(params?: ApiRolesPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDto>> {
    const obs = apiRolesPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesPost$Plain(params?: ApiRolesPost$Plain$Params, context?: HttpContext): Promise<RolDto> {
    const resp = this.apiRolesPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDto>): RolDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesPost$Json$Response(params?: ApiRolesPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<RolDto>> {
    const obs = apiRolesPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolesPost$Json(params?: ApiRolesPost$Json$Params, context?: HttpContext): Promise<RolDto> {
    const resp = this.apiRolesPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<RolDto>): RolDto => r.body);
  }

  /** Path part for operation `apiRolesCambiarEstadoIdPut()` */
  static readonly ApiRolesCambiarEstadoIdPutPath = '/api/Roles/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolesCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesCambiarEstadoIdPut$Response(params: ApiRolesCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiRolesCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolesCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRolesCambiarEstadoIdPut(params: ApiRolesCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiRolesCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
