/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AdmUsuario } from '../models/adm-usuario';
import { apiUsuariosCambiarEstadoIdPut } from '../fn/usuarios/api-usuarios-cambiar-estado-id-put';
import { ApiUsuariosCambiarEstadoIdPut$Params } from '../fn/usuarios/api-usuarios-cambiar-estado-id-put';
import { apiUsuariosIdGet$Json } from '../fn/usuarios/api-usuarios-id-get-json';
import { ApiUsuariosIdGet$Json$Params } from '../fn/usuarios/api-usuarios-id-get-json';
import { apiUsuariosIdGet$Plain } from '../fn/usuarios/api-usuarios-id-get-plain';
import { ApiUsuariosIdGet$Plain$Params } from '../fn/usuarios/api-usuarios-id-get-plain';
import { apiUsuariosIdPut } from '../fn/usuarios/api-usuarios-id-put';
import { ApiUsuariosIdPut$Params } from '../fn/usuarios/api-usuarios-id-put';
import { apiUsuariosPaginacionGet$Json } from '../fn/usuarios/api-usuarios-paginacion-get-json';
import { ApiUsuariosPaginacionGet$Json$Params } from '../fn/usuarios/api-usuarios-paginacion-get-json';
import { apiUsuariosPaginacionGet$Plain } from '../fn/usuarios/api-usuarios-paginacion-get-plain';
import { ApiUsuariosPaginacionGet$Plain$Params } from '../fn/usuarios/api-usuarios-paginacion-get-plain';
import { apiUsuariosPermisosGet$Json } from '../fn/usuarios/api-usuarios-permisos-get-json';
import { ApiUsuariosPermisosGet$Json$Params } from '../fn/usuarios/api-usuarios-permisos-get-json';
import { apiUsuariosPermisosGet$Plain } from '../fn/usuarios/api-usuarios-permisos-get-plain';
import { ApiUsuariosPermisosGet$Plain$Params } from '../fn/usuarios/api-usuarios-permisos-get-plain';
import { apiUsuariosPost$Json } from '../fn/usuarios/api-usuarios-post-json';
import { ApiUsuariosPost$Json$Params } from '../fn/usuarios/api-usuarios-post-json';
import { apiUsuariosPost$Plain } from '../fn/usuarios/api-usuarios-post-plain';
import { ApiUsuariosPost$Plain$Params } from '../fn/usuarios/api-usuarios-post-plain';
import { UsuarioDto } from '../models/usuario-dto';
import { UsuarioDtoPaginacionDto } from '../models/usuario-dto-paginacion-dto';

@Injectable({ providedIn: 'root' })
export class UsuariosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsuariosPaginacionGet()` */
  static readonly ApiUsuariosPaginacionGetPath = '/api/Usuarios/paginacion';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPaginacionGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPaginacionGet$Plain$Response(params?: ApiUsuariosPaginacionGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDtoPaginacionDto>> {
    const obs = apiUsuariosPaginacionGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPaginacionGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPaginacionGet$Plain(params?: ApiUsuariosPaginacionGet$Plain$Params, context?: HttpContext): Promise<UsuarioDtoPaginacionDto> {
    const resp = this.apiUsuariosPaginacionGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDtoPaginacionDto>): UsuarioDtoPaginacionDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPaginacionGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPaginacionGet$Json$Response(params?: ApiUsuariosPaginacionGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDtoPaginacionDto>> {
    const obs = apiUsuariosPaginacionGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPaginacionGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPaginacionGet$Json(params?: ApiUsuariosPaginacionGet$Json$Params, context?: HttpContext): Promise<UsuarioDtoPaginacionDto> {
    const resp = this.apiUsuariosPaginacionGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDtoPaginacionDto>): UsuarioDtoPaginacionDto => r.body);
  }

  /** Path part for operation `apiUsuariosIdGet()` */
  static readonly ApiUsuariosIdGetPath = '/api/Usuarios/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosIdGet$Plain$Response(params: ApiUsuariosIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = apiUsuariosIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosIdGet$Plain(params: ApiUsuariosIdGet$Plain$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.apiUsuariosIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosIdGet$Json$Response(params: ApiUsuariosIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = apiUsuariosIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosIdGet$Json(params: ApiUsuariosIdGet$Json$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.apiUsuariosIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /** Path part for operation `apiUsuariosIdPut()` */
  static readonly ApiUsuariosIdPutPath = '/api/Usuarios/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosIdPut$Response(params: ApiUsuariosIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUsuariosIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosIdPut(params: ApiUsuariosIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUsuariosIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiUsuariosPermisosGet()` */
  static readonly ApiUsuariosPermisosGetPath = '/api/Usuarios/permisos';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPermisosGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPermisosGet$Plain$Response(params?: ApiUsuariosPermisosGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<string>>> {
    const obs = apiUsuariosPermisosGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPermisosGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPermisosGet$Plain(params?: ApiUsuariosPermisosGet$Plain$Params, context?: HttpContext): Promise<Array<string>> {
    const resp = this.apiUsuariosPermisosGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<string>>): Array<string> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPermisosGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPermisosGet$Json$Response(params?: ApiUsuariosPermisosGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<string>>> {
    const obs = apiUsuariosPermisosGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPermisosGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosPermisosGet$Json(params?: ApiUsuariosPermisosGet$Json$Params, context?: HttpContext): Promise<Array<string>> {
    const resp = this.apiUsuariosPermisosGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<string>>): Array<string> => r.body);
  }

  /** Path part for operation `apiUsuariosPost()` */
  static readonly ApiUsuariosPostPath = '/api/Usuarios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosPost$Plain$Response(params?: ApiUsuariosPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<AdmUsuario>> {
    const obs = apiUsuariosPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosPost$Plain(params?: ApiUsuariosPost$Plain$Params, context?: HttpContext): Promise<AdmUsuario> {
    const resp = this.apiUsuariosPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdmUsuario>): AdmUsuario => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosPost$Json$Response(params?: ApiUsuariosPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<AdmUsuario>> {
    const obs = apiUsuariosPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuariosPost$Json(params?: ApiUsuariosPost$Json$Params, context?: HttpContext): Promise<AdmUsuario> {
    const resp = this.apiUsuariosPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<AdmUsuario>): AdmUsuario => r.body);
  }

  /** Path part for operation `apiUsuariosCambiarEstadoIdPut()` */
  static readonly ApiUsuariosCambiarEstadoIdPutPath = '/api/Usuarios/cambiarEstado/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuariosCambiarEstadoIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosCambiarEstadoIdPut$Response(params: ApiUsuariosCambiarEstadoIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUsuariosCambiarEstadoIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuariosCambiarEstadoIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuariosCambiarEstadoIdPut(params: ApiUsuariosCambiarEstadoIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUsuariosCambiarEstadoIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
