/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiZonasCantonesGet$Json } from '../fn/zonas/api-zonas-cantones-get-json';
import { ApiZonasCantonesGet$Json$Params } from '../fn/zonas/api-zonas-cantones-get-json';
import { apiZonasCantonesGet$Plain } from '../fn/zonas/api-zonas-cantones-get-plain';
import { ApiZonasCantonesGet$Plain$Params } from '../fn/zonas/api-zonas-cantones-get-plain';
import { apiZonasParroquiasGet$Json } from '../fn/zonas/api-zonas-parroquias-get-json';
import { ApiZonasParroquiasGet$Json$Params } from '../fn/zonas/api-zonas-parroquias-get-json';
import { apiZonasParroquiasGet$Plain } from '../fn/zonas/api-zonas-parroquias-get-plain';
import { ApiZonasParroquiasGet$Plain$Params } from '../fn/zonas/api-zonas-parroquias-get-plain';
import { apiZonasProvinciasGet$Json } from '../fn/zonas/api-zonas-provincias-get-json';
import { ApiZonasProvinciasGet$Json$Params } from '../fn/zonas/api-zonas-provincias-get-json';
import { apiZonasProvinciasGet$Plain } from '../fn/zonas/api-zonas-provincias-get-plain';
import { ApiZonasProvinciasGet$Plain$Params } from '../fn/zonas/api-zonas-provincias-get-plain';
import { apiZonasZonasGet$Json } from '../fn/zonas/api-zonas-zonas-get-json';
import { ApiZonasZonasGet$Json$Params } from '../fn/zonas/api-zonas-zonas-get-json';
import { apiZonasZonasGet$Plain } from '../fn/zonas/api-zonas-zonas-get-plain';
import { ApiZonasZonasGet$Plain$Params } from '../fn/zonas/api-zonas-zonas-get-plain';
import { Canton } from '../models/canton';
import { Parroquia } from '../models/parroquia';
import { Provincia } from '../models/provincia';
import { Zona } from '../models/zona';

@Injectable({ providedIn: 'root' })
export class ZonasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiZonasProvinciasGet()` */
  static readonly ApiZonasProvinciasGetPath = '/api/Zonas/provincias';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasProvinciasGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasProvinciasGet$Plain$Response(params?: ApiZonasProvinciasGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Provincia>>> {
    const obs = apiZonasProvinciasGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasProvinciasGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasProvinciasGet$Plain(params?: ApiZonasProvinciasGet$Plain$Params, context?: HttpContext): Promise<Array<Provincia>> {
    const resp = this.apiZonasProvinciasGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Provincia>>): Array<Provincia> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasProvinciasGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasProvinciasGet$Json$Response(params?: ApiZonasProvinciasGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Provincia>>> {
    const obs = apiZonasProvinciasGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasProvinciasGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasProvinciasGet$Json(params?: ApiZonasProvinciasGet$Json$Params, context?: HttpContext): Promise<Array<Provincia>> {
    const resp = this.apiZonasProvinciasGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Provincia>>): Array<Provincia> => r.body);
  }

  /** Path part for operation `apiZonasCantonesGet()` */
  static readonly ApiZonasCantonesGetPath = '/api/Zonas/cantones';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasCantonesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasCantonesGet$Plain$Response(params?: ApiZonasCantonesGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Canton>>> {
    const obs = apiZonasCantonesGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasCantonesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasCantonesGet$Plain(params?: ApiZonasCantonesGet$Plain$Params, context?: HttpContext): Promise<Array<Canton>> {
    const resp = this.apiZonasCantonesGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Canton>>): Array<Canton> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasCantonesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasCantonesGet$Json$Response(params?: ApiZonasCantonesGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Canton>>> {
    const obs = apiZonasCantonesGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasCantonesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasCantonesGet$Json(params?: ApiZonasCantonesGet$Json$Params, context?: HttpContext): Promise<Array<Canton>> {
    const resp = this.apiZonasCantonesGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Canton>>): Array<Canton> => r.body);
  }

  /** Path part for operation `apiZonasParroquiasGet()` */
  static readonly ApiZonasParroquiasGetPath = '/api/Zonas/parroquias';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasParroquiasGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasParroquiasGet$Plain$Response(params?: ApiZonasParroquiasGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Parroquia>>> {
    const obs = apiZonasParroquiasGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasParroquiasGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasParroquiasGet$Plain(params?: ApiZonasParroquiasGet$Plain$Params, context?: HttpContext): Promise<Array<Parroquia>> {
    const resp = this.apiZonasParroquiasGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Parroquia>>): Array<Parroquia> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasParroquiasGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasParroquiasGet$Json$Response(params?: ApiZonasParroquiasGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Parroquia>>> {
    const obs = apiZonasParroquiasGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasParroquiasGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasParroquiasGet$Json(params?: ApiZonasParroquiasGet$Json$Params, context?: HttpContext): Promise<Array<Parroquia>> {
    const resp = this.apiZonasParroquiasGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Parroquia>>): Array<Parroquia> => r.body);
  }

  /** Path part for operation `apiZonasZonasGet()` */
  static readonly ApiZonasZonasGetPath = '/api/Zonas/zonas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasZonasGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasZonasGet$Plain$Response(params?: ApiZonasZonasGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Zona>>> {
    const obs = apiZonasZonasGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasZonasGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasZonasGet$Plain(params?: ApiZonasZonasGet$Plain$Params, context?: HttpContext): Promise<Array<Zona>> {
    const resp = this.apiZonasZonasGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Zona>>): Array<Zona> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiZonasZonasGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasZonasGet$Json$Response(params?: ApiZonasZonasGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Zona>>> {
    const obs = apiZonasZonasGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiZonasZonasGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiZonasZonasGet$Json(params?: ApiZonasZonasGet$Json$Params, context?: HttpContext): Promise<Array<Zona>> {
    const resp = this.apiZonasZonasGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Zona>>): Array<Zona> => r.body);
  }

}
