/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Jurisdiccion } from '../../models/jurisdiccion';
import { ListaElectoralPaginacionDto } from '../../models/lista-electoral-paginacion-dto';

export interface ApiListasElectoralPaginacionGet$Json$Params {
  pagina?: number;
  pageSize?: number;
  buscar?: string;
  jurisdiccion?: Jurisdiccion;
}

export function apiListasElectoralPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiListasElectoralPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaElectoralPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiListasElectoralPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('buscar', params.buscar, {});
    rb.query('jurisdiccion', params.jurisdiccion, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaElectoralPaginacionDto>;
    })
  );
}

apiListasElectoralPaginacionGet$Json.PATH = '/api/ListasElectoral/paginacion';
