/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListaElectoral } from '../../models/lista-electoral';

export interface ApiListasElectoralPost$Plain$Params {
      body?: ListaElectoral
}

export function apiListasElectoralPost$Plain(http: HttpClient, rootUrl: string, params?: ApiListasElectoralPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaElectoral>> {
  const rb = new RequestBuilder(rootUrl, apiListasElectoralPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaElectoral>;
    })
  );
}

apiListasElectoralPost$Plain.PATH = '/api/ListasElectoral';
