/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidatoDtoPaginacionDto } from '../../models/candidato-dto-paginacion-dto';
import { TipoCandidato } from '../../models/tipo-candidato';

export interface ApiCandidatosPaginacionGet$Json$Params {
  eleccionId?: string;
  pagina?: number;
  pageSize?: number;
  busqueda?: string;
  tipoCandidato?: TipoCandidato;
  listaElectoralId?: string;
}

export function apiCandidatosPaginacionGet$Json(http: HttpClient, rootUrl: string, params?: ApiCandidatosPaginacionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidatoDtoPaginacionDto>> {
  const rb = new RequestBuilder(rootUrl, apiCandidatosPaginacionGet$Json.PATH, 'get');
  if (params) {
    rb.query('eleccionId', params.eleccionId, {});
    rb.query('pagina', params.pagina, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('busqueda', params.busqueda, {});
    rb.query('tipoCandidato', params.tipoCandidato, {});
    rb.query('listaElectoralId', params.listaElectoralId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidatoDtoPaginacionDto>;
    })
  );
}

apiCandidatosPaginacionGet$Json.PATH = '/api/Candidatos/paginacion';
