/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Candidato } from '../../models/candidato';

export interface ApiCandidatosPost$Json$Params {
      body?: Candidato
}

export function apiCandidatosPost$Json(http: HttpClient, rootUrl: string, params?: ApiCandidatosPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Candidato>> {
  const rb = new RequestBuilder(rootUrl, apiCandidatosPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Candidato>;
    })
  );
}

apiCandidatosPost$Json.PATH = '/api/Candidatos';
