/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidatoDto } from '../../models/candidato-dto';

export interface ApiCandidatosIdGet$Plain$Params {
  id: string;
}

export function apiCandidatosIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCandidatosIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidatoDto>> {
  const rb = new RequestBuilder(rootUrl, apiCandidatosIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidatoDto>;
    })
  );
}

apiCandidatosIdGet$Plain.PATH = '/api/Candidatos/{id}';
